---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: sock-shop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YmFsZF9mYWtlX3Bhc3M=  # Base64-encoded password 











